NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: intermediatecerts/localhost-7779.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: intermediatecerts/localhost-7779.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: intermediatecerts/localhost-7779.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: intermediatecerts/localhost-7779.pem
    OrganizationalUnitIdentifier: orderer
